apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cve
  template:
    metadata:
      labels:
        app: cve
    spec:
      containers:
      - name: cve-api
        image: diordon/finalcicd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_PATH
          value: /data/cvewatch.db
        volumeMounts:
        - name: cve-db
          mountPath: /data
      volumes:
      - name: cve-db
        persistentVolumeClaim:
          claimName: cve-db-pvc

