Paste (replace YOUR_DOCKERHUB_USER):
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 1
  selector:
    matchLabels: { app: hello }
  template:
    metadata:
      labels: { app: hello }
    spec:
      containers:
      - name: hello
        image: diaordon/finalcicd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
