apiVersion: v1
kind: Service
metadata:
  name: cve-svc
  labels:
    app: cve-watch
spec:
  type: ClusterIP
  selector:
    app: cve-watch
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP

